# frozen_string_literal: true

require "black_hole_struct"

module Kube
  module Schema
    class Resource

      # Subclasses generated by Instance#[] have a class-level .schema
      # which is a JSONSchemer::Schema object, and .defaults which
      # provides apiVersion and kind derived from the GVK metadata.
      def initialize(hash = {}, &block)
        hash = deep_stringify_keys(hash)

        @data = BlackHoleStruct.new(hash)
        @data.instance_exec(&block) if block
      end

      # Gets overridden by the factory in Kube::Schema::Instance
      def self.schema
        nil
      end

      # Gets overridden by the factory in Kube::Schema::Instance.
      # Returns a frozen Hash like { "apiVersion" => "apps/v1", "kind" => "Deployment" }
      def self.defaults
        nil
      end

      def valid?
        return true if self.class.schema.nil?

        self.class.schema.valid?(deep_stringify_keys(to_h))
      end

      # Like #valid? but raises Kube::ValidationError with details on failure.
      # The error message includes the resource kind and name for context.
      def valid!
        return true if self.class.schema.nil?

        data = deep_stringify_keys(to_h)
        errors = self.class.schema.validate(data).to_a

        unless errors.empty?
          kind = self.class.defaults&.dig("kind")
          name = data.dig("metadata", "name")
          raise Kube::ValidationError.new(errors, kind: kind, name: name, manifest: data)
        end

        true
      end

      # Returns the resource data as a Hash. Defaults (apiVersion, kind)
      # from the schema are authoritative and cannot be overridden --
      # they are facts derived from the GVK metadata.
      def to_h
        defaults = self.class.defaults
        data = @data.to_h

        if defaults
          symbolized = deep_symbolize_keys(defaults)
          # Defaults go first (for key ordering), then user data minus
          # any attempts to override the authoritative keys.
          symbolized.merge(data.reject { |k, _| symbolized.key?(k) })
        else
          data
        end
      end

      # Serializes to clean Kubernetes YAML.
      # Raises Kube::ValidationError if the resource is not valid.
      def to_yaml
        valid!
        deep_stringify_keys(to_h).to_yaml
      end

      def ==(other)
        other.is_a?(Resource) && to_h == other.to_h
      end

      private

        def deep_stringify_keys(obj)
          case obj
          when Hash
            obj.each_with_object({}) do |(k, v), result|
              result[k.to_s] = deep_stringify_keys(v)
            end
          when Array
            obj.map { |v| deep_stringify_keys(v) }
          else
            obj
          end
        end

        def deep_symbolize_keys(obj)
          case obj
          when Hash
            obj.each_with_object({}) do |(k, v), result|
              result[k.to_sym] = deep_symbolize_keys(v)
            end
          when Array
            obj.map { |v| deep_symbolize_keys(v) }
          else
            obj
          end
        end
    end
  end
end
