# frozen_string_literal: true

require "ostruct"

module KubeSchema
  class Resource
    attr_reader :schema

    # Subclasses generated by Instance#[] have a class-level .schema.
    # When called directly via KubeSchema.parse(hash), the hash is passed in.
    def initialize(hash = nil, &block)
      @schema = hash || self.class.schema
      @data = OpenStruct.new(@schema)
      @data.instance_exec(&block) if block
    end

    def self.schema
      nil
    end

    def to_h
      @data.to_h
    end

    def ==(other)
      other.is_a?(Resource) && to_h == other.to_h
    end

    def respond_to_missing?(method, include_private = false)
      @data.respond_to?(method, include_private) || super
    end

    private

    def method_missing(method, *args, &block)
      if @data.respond_to?(method)
        @data.send(method, *args, &block)
      else
        super
      end
    end
  end
end
