# frozen_string_literal: true

require "ostruct"
require "black_hole_struct"
require "json_schemer"

module KubeSchema
  class Resource

    # Subclasses generated by Instance#[] have a class-level .schema.
    def initialize(hash = {}, &block)
      hash = deep_stringify_keys(hash)

      if self.class.schema
        schemer = JSONSchemer.schema(self.class.schema, insert_property_defaults: true)
        schemer.valid?(hash)
      end

      @data = BlackHoleStruct.new(hash)
      @data.instance_exec(&block) if block
    end

    # Gets overridden by the factory in KubeSchema::Instance
    def self.schema
      nil
    end

    def valid?
      return true if self.class.schema.nil?

      schemer = JSONSchemer.schema(self.class.schema)
      schemer.valid?(deep_stringify_keys(to_h))
    end

    def to_h
      @data.to_h
    end

    def ==(other)
      other.is_a?(Resource) && to_h == other.to_h
    end

    private

      def deep_stringify_keys(obj)
        case obj
        when Hash
          obj.each_with_object({}) do |(k, v), result|
            result[k.to_s] = deep_stringify_keys(v)
          end
        when Array
          obj.map { |v| deep_stringify_keys(v) }
        else
          obj
        end
      end
  end
end
