# frozen_string_literal: true

require "ostruct"
require "black_hole_struct"

module KubeSchema
  class Resource

    # Subclasses generated by Instance#[] have a class-level .schema.
    # When called directly via KubeSchema.parse(hash), the hash is passed in.
    def initialize(hash = nil, &block)
      @data = BlackHoleStruct.new(hash)
      @data.instance_exec(&block) if block
    end

    # Gets overridden by the factory in KubeSchema::Instance
    def self.schema
      nil
    end

    def to_h
      @data.to_h
    end

    def ==(other)
      other.is_a?(Resource) && to_h == other.to_h
    end
  end
end
