name: Convert Kubernetes Schemas

on:
  workflow_dispatch:
  schedule:
    # “At 10:10 on every 2nd day-of-month.”
    - cron: "10 10 */2 * *"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: schemas

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: bundle install
        run: bundle install

      - name: convert-the-schemas-bro
        run: bin/convert-schemas

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: schemas
          commit_message: "Workflow Run: convert-schemas.yml"
          commit_user_name: Nathan K
          commit_user_email: nathankidd@hey.com
          commit_author: Nathan K <nathankidd@hey.com>
