name: Update Kubernetes Schemas

on:
  workflow_dispatch:
  schedule:
    # “At 10:10 on every 2nd day-of-month.”
    - cron: "10 10 */2 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: schemas

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: update-the-schemas-bro
        run: nix develop --command bin/update-schemas

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: schemas
          commit_message: "Workflow Run: update-schemas.yml"
          commit_user_name: Nathan K
          commit_user_email: nathankidd@hey.com
          commit_author: Nathan K <nathankidd@hey.com>
