name: Update Kubernetes Schemas

on:
  workflow_dispatch:
  schedule:
    # “At 10:10 on every 2nd day-of-month.”
    - cron: "10 10 */2 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: schemas

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install openapi2jsonschema
        run: |
          pip install --upgrade pip
          pip install openapi2jsonschema
          pip install --upgrade "pyyaml>=6.0"

      - name: bundle install
        run: bundle install

      - name: update-the-schemas-bro
        run: bin/update-schemas

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: schemas
          commit_message: "Workflow Run: update-schemas.yml"
          commit_user_name: Nathan K
          commit_user_email: nathankidd@hey.com
          commit_author: Nathan K <nathankidd@hey.com>
