name: Update CRD Schemas

on:
  workflow_dispatch:
  schedule:
    # “At 10:10 on every 2nd day-of-month.”
    - cron: "10 10 */2 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout schemas branch
        uses: actions/checkout@v4
        with:
          ref: schemas

      - name: download crds-catalog index
        run: curl -fsSL -o crds-catalog.yaml https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/index.yaml

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: download the crds from catalog
        run: "bin/update-crds"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: schemas
          commit_message: "Update crds-catalog.yaml"
          commit_user_name: Nathan K
          commit_user_email: nathankidd@hey.com
          commit_author: Nathan K <nathankidd@hey.com>
